/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UpgradableGreeterV1 } from "./UpgradableGreeterV1";
export type { UpgradableGreeterV2 } from "./UpgradableGreeterV2";
